# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u5e7f\u544a\u6807\u9898')),
                ('description', models.CharField(max_length=200, verbose_name='\u5e7f\u544a\u63cf\u8ff0')),
                ('image_url', models.ImageField(upload_to='ad/%Y/%m', verbose_name='\u56fe\u7247\u8def\u5f84')),
                ('callback_url', models.URLField(blank=True, null=True, verbose_name='\u8fde\u63a5\u5730\u5740')),
                ('date_publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('order', models.IntegerField(default=9, verbose_name='\u6392\u5217\u987a\u5e8f(\u4ece\u5c0f\u5230\u5927)')),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name_plural': '\u8f6e\u64ad\u5e7f\u544a',
                'db_table': 'ad',
                'default_permissions': ('read', 'change', 'add', 'delete'),
                'verbose_name': '\u8f6e\u64ad\u5e7f\u544a',
            },
        ),
        migrations.CreateModel(
            name='ApplicationCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u6848\u4f8b\u540d\u79f0')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='\u6848\u4f8b\u63cf\u8ff0')),
                ('image', models.ImageField(upload_to='application/%Y/%m', verbose_name='\u6848\u4f8b\u56fe\u7247')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u6848\u4f8b\u5185\u5bb9')),
                ('show_index', models.NullBooleanField(default=False, help_text='\u6700\u591a9\u6761', verbose_name='\u662f\u5426\u5c55\u793a\u5230\u9996\u9875')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u5e94\u7528\u6848\u4f8b',
                'db_table': 'application_case',
                'default_permissions': ('read', 'change', 'add', 'delete'),
                'verbose_name': '\u5e94\u7528\u6848\u4f8b',
            },
        ),
        migrations.CreateModel(
            name='CompanyCulture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('order', models.IntegerField(default=9, verbose_name='\u6392\u5217\u987a\u5e8f(\u4ece\u5c0f\u5230\u5927)')),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name_plural': '\u5173\u4e8e\u6211\u4eec-\u516c\u53f8\u6587\u5316',
                'db_table': 'company_culture',
                'default_permissions': ('read', 'change', 'add', 'delete'),
                'verbose_name': '\u5173\u4e8e\u6211\u4eec-\u516c\u53f8\u6587\u5316',
            },
        ),
        migrations.CreateModel(
            name='CompanyIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('order', models.IntegerField(default=9, verbose_name='\u6392\u5217\u987a\u5e8f(\u4ece\u5c0f\u5230\u5927)')),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name_plural': '\u5173\u4e8e\u6211\u4eec-\u516c\u53f8\u7b80\u4ecb',
                'db_table': 'company_intro',
                'default_permissions': ('read', 'change', 'add', 'delete'),
                'verbose_name': '\u5173\u4e8e\u6211\u4eec-\u516c\u53f8\u7b80\u4ecb',
            },
        ),
        migrations.CreateModel(
            name='CompanyStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('order', models.IntegerField(default=9, verbose_name='\u6392\u5217\u987a\u5e8f(\u4ece\u5c0f\u5230\u5927)')),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name_plural': '\u5173\u4e8e\u6211\u4eec-\u7ec4\u7ec7\u67b6\u6784',
                'db_table': 'company_structure',
                'default_permissions': ('read', 'change', 'add', 'delete'),
                'verbose_name': '\u5173\u4e8e\u6211\u4eec-\u7ec4\u7ec7\u67b6\u6784',
            },
        ),
        migrations.CreateModel(
            name='CompanyVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u89c6\u5c4f\u6807\u9898')),
                ('video_img', models.ImageField(upload_to='video_img/%Y/%m', verbose_name='\u89c6\u5c4f\u56fe\u7247')),
                ('url', models.CharField(max_length=500, verbose_name='\u89c6\u5c4f\u94fe\u63a5')),
                ('describe', models.CharField(max_length=500, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u516c\u53f8\u89c6\u9891',
                'db_table': 'company_video',
                'default_permissions': ('read', 'change', 'add', 'delete'),
                'verbose_name': '\u516c\u53f8\u89c6\u9891',
            },
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255, verbose_name='\u516c\u53f8\u5927\u533a')),
                ('phone', models.CharField(max_length=100, verbose_name='\u7535\u8bdd')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('address', models.CharField(max_length=500, verbose_name='\u5730\u5740')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u8054\u7cfb\u65b9\u5f0f',
                'db_table': 'contact_list',
                'default_permissions': ('read', 'change', 'add', 'delete'),
                'verbose_name': '\u8054\u7cfb\u65b9\u5f0f',
            },
        ),
        migrations.CreateModel(
            name='DevelopHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('content', models.CharField(blank=True, max_length=2000, null=True, verbose_name='\u5185\u5bb9')),
                ('date_time', models.DateField(default=django.utils.timezone.now, verbose_name='\u65f6\u95f4')),
            ],
            options={
                'ordering': ['date_time'],
                'verbose_name_plural': '\u5173\u4e8e\u6211\u4eec-\u53d1\u5c55\u5386\u7a0b',
                'db_table': 'develop_history',
                'default_permissions': ('read', 'change', 'add', 'delete'),
                'verbose_name': '\u5173\u4e8e\u6211\u4eec-\u53d1\u5c55\u5386\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u65b0\u95fb\u6807\u9898')),
                ('news_image', models.ImageField(upload_to='news/%Y/%m', verbose_name='\u65b0\u95fb\u56fe\u7247')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u65b0\u95fb\u5185\u5bb9')),
                ('eye_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u6d4f\u89c8\u91cf')),
                ('thumb_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u70b9\u8d5e\u91cf')),
                ('date_publish', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('show_index', models.NullBooleanField(default=False, help_text='\u76ee\u524d\u9996\u9875\u53ea\u80fd\u663e\u793a5\u6761', verbose_name='\u662f\u5426\u5c55\u793a\u5230\u9996\u9875')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7f16\u8f91\u8005')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u65b0\u95fb',
                'db_table': 'news',
                'default_permissions': ('read', 'change', 'add', 'delete'),
                'verbose_name': '\u65b0\u95fb',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u4ea7\u54c1\u7b80\u4ecb')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u4ea7\u54c1\u8be6\u60c5')),
                ('image', models.ImageField(upload_to='product/%Y/%m', verbose_name='\u4ea7\u54c1\u56fe\u7247')),
                ('parameter', models.TextField(blank=True, null=True, verbose_name='\u53c2\u6570')),
                ('model', models.TextField(blank=True, null=True, verbose_name='\u9009\u578b')),
                ('test', models.TextField(blank=True, null=True, verbose_name='\u6d4b\u8bd5')),
                ('application', models.TextField(blank=True, null=True, verbose_name='\u5e94\u7528')),
                ('download', models.FileField(blank=True, null=True, upload_to='product/download/%Y/%m', verbose_name='\u8d44\u6599\u4e0b\u8f7d')),
                ('show_index', models.NullBooleanField(default=False, verbose_name='\u662f\u5426\u5c55\u793a\u5230\u9996\u9875')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u4ea7\u54c1',
                'db_table': 'product',
                'default_permissions': ('read', 'change', 'add', 'delete'),
                'verbose_name': '\u4ea7\u54c1',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u4ea7\u54c1\u5206\u7c7b')),
                ('image', models.ImageField(upload_to='product_category/%Y/%m', verbose_name='\u4ea7\u54c1\u5206\u7c7b\u56fe\u7247')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u5206\u7c7b\u63cf\u8ff0')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u4ea7\u54c1\u5206\u7c7b',
                'db_table': 'product_category',
                'default_permissions': ('read', 'change', 'add', 'delete'),
                'verbose_name': '\u4ea7\u54c1\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u804c\u4f4d\u540d\u79f0')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u804c\u4f4d\u5185\u5bb9')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u8054\u7cfb\u6211\u4eec-\u62db\u8058\u4eba\u624d',
                'db_table': 'recruit',
                'default_permissions': ('read', 'change', 'add', 'delete'),
                'verbose_name': '\u8054\u7cfb\u6211\u4eec-\u62db\u8058\u4eba\u624d',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u670d\u52a1\u540d\u79f0')),
                ('image', models.ImageField(upload_to='service/%Y/%m', verbose_name='\u670d\u52a1\u56fe\u7247')),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u8be6\u7ec6\u5185\u5bb9')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u670d\u52a1\u9879\u76ee',
                'db_table': 'service',
                'default_permissions': ('read', 'change', 'add', 'delete'),
                'verbose_name': '\u670d\u52a1\u9879\u76ee',
            },
        ),
        migrations.CreateModel(
            name='SiteMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='\u59d3\u540d')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5355\u4f4d\u540d\u79f0')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('phone_num', models.CharField(max_length=255, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('interest_product', models.CharField(max_length=1000, verbose_name='\u611f\u5174\u8da3\u4ea7\u54c1')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '\u7f51\u7ad9\u7559\u8a00',
                'db_table': 'site_message',
                'default_permissions': ('read', 'change', 'add', 'delete'),
                'verbose_name': '\u7f51\u7ad9\u7559\u8a00',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ProductCategory', verbose_name='\u4ea7\u54c1\u5206\u7c7b'),
        ),
    ]
