# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170810_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemessage',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='sitemessage',
            name='interest_product',
        ),
    ]
