# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170810_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='\u4ea7\u54c1\u5206\u7c7b\u5185\u5bb9'),
        ),
    ]
