# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_productcategory_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='facsimile',
            field=models.CharField(default=1, max_length=255, verbose_name='\u4f20\u771f'),
            preserve_default=False,
        ),
    ]
